// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderService.proto

package protoGo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeliveryAddress      string     `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DueDate              int32      `protobuf:"varint,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Items                []*Product `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d3238042c2687a, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetDeliveryAddress() string {
	if m != nil {
		return m.DeliveryAddress
	}
	return ""
}

func (m *Order) GetDueDate() int32 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

func (m *Order) GetItems() []*Product {
	if m != nil {
		return m.Items
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Qty                  int32    `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d3238042c2687a, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Product) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

// Created a blank get request
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d3238042c2687a, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type CreateOrderResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Order                *Order   `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Orders               []*Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d3238042c2687a, []int{3}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CreateOrderResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d3238042c2687a, []int{4}
}

func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(m, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "model.order.Order")
	proto.RegisterType((*Product)(nil), "model.order.Product")
	proto.RegisterType((*GetRequest)(nil), "model.order.GetRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "model.order.CreateOrderResponse")
	proto.RegisterType((*GetOrdersResponse)(nil), "model.order.GetOrdersResponse")
}

func init() { proto.RegisterFile("orderService.proto", fileDescriptor_93d3238042c2687a) }

var fileDescriptor_93d3238042c2687a = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3d, 0x53, 0xc2, 0x40,
	0x14, 0x24, 0x84, 0xf0, 0xf1, 0xc2, 0x28, 0x3e, 0x9d, 0x31, 0x52, 0x38, 0x99, 0xab, 0x22, 0x45,
	0x0a, 0x2c, 0x2d, 0x18, 0x3f, 0x29, 0x71, 0xce, 0xce, 0x86, 0x89, 0xb9, 0x57, 0x64, 0x06, 0x3c,
	0xb8, 0xbb, 0x30, 0xc3, 0x0f, 0xb0, 0xf0, 0x47, 0xf8, 0x5f, 0x1d, 0x2e, 0x01, 0x89, 0xd2, 0xd8,
	0x6d, 0xf6, 0xed, 0xdd, 0xee, 0xbe, 0x1c, 0xa0, 0x54, 0x82, 0xd4, 0x0b, 0xa9, 0x55, 0x96, 0x52,
	0xbc, 0x50, 0xd2, 0x48, 0xf4, 0xe7, 0x52, 0xd0, 0x2c, 0xb6, 0x13, 0xf6, 0xe9, 0x80, 0x37, 0xd9,
	0x20, 0x3c, 0x82, 0x7a, 0x26, 0x02, 0x27, 0x74, 0xa2, 0x0e, 0xaf, 0x67, 0x02, 0xaf, 0xa0, 0x27,
	0x68, 0x96, 0xad, 0x48, 0xad, 0xa7, 0x89, 0x10, 0x8a, 0xb4, 0x0e, 0xea, 0x76, 0x7a, 0xbc, 0xe5,
	0x6f, 0x0b, 0x1a, 0x2f, 0xa0, 0x2d, 0x72, 0x9a, 0x8a, 0xc4, 0x50, 0xe0, 0x86, 0x4e, 0xe4, 0xf1,
	0x96, 0xc8, 0xe9, 0x21, 0x31, 0x84, 0x03, 0xf0, 0x32, 0x43, 0x73, 0x1d, 0x34, 0x42, 0x37, 0xf2,
	0x87, 0x67, 0xf1, 0x9e, 0x79, 0xfc, 0xac, 0xa4, 0xc8, 0x53, 0xc3, 0x0b, 0x09, 0x1b, 0x41, 0xab,
	0x64, 0xfe, 0x84, 0x41, 0x68, 0x08, 0xd2, 0x69, 0x19, 0xc0, 0x62, 0xec, 0x81, 0xbb, 0x34, 0xeb,
	0xd2, 0x70, 0x03, 0x59, 0x17, 0x60, 0x4c, 0x86, 0xd3, 0x32, 0x27, 0x6d, 0xd8, 0x87, 0x03, 0xa7,
	0xf7, 0x8a, 0x12, 0x43, 0xb6, 0x20, 0x27, 0xbd, 0x90, 0xef, 0x9a, 0x30, 0x80, 0x56, 0x6a, 0xe9,
	0xc2, 0xa0, 0xcd, 0xb7, 0x9f, 0x18, 0x81, 0x67, 0x83, 0x59, 0x1b, 0x7f, 0x88, 0x95, 0xb0, 0xc5,
	0x25, 0x85, 0x00, 0x07, 0xd0, 0xb4, 0x40, 0x07, 0xae, 0xed, 0x75, 0x48, 0x5a, 0x2a, 0xd8, 0x08,
	0x4e, 0xc6, 0x64, 0x2c, 0xa7, 0x77, 0x21, 0xfe, 0x71, 0xc1, 0xf0, 0xcb, 0x81, 0xee, 0x64, 0xef,
	0x3f, 0xe2, 0x23, 0xf8, 0x7b, 0xc5, 0xf0, 0xc0, 0xd9, 0x7e, 0x58, 0xe1, 0x0e, 0xac, 0x81, 0xd5,
	0xf0, 0x09, 0x3a, 0xbb, 0x60, 0x78, 0x5e, 0x39, 0xf0, 0xb3, 0xc6, 0xfe, 0xe5, 0xef, 0x41, 0xb5,
	0x09, 0xab, 0xdd, 0xf9, 0xaf, 0x9d, 0xf8, 0xc6, 0xbe, 0xad, 0xb1, 0x7c, 0x6b, 0x5a, 0x70, 0xfd,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xc5, 0x22, 0xac, 0x7a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *Order, opts ...client.CallOption) (*CreateOrderResponse, error)
	GetOrders(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetOrdersResponse, error)
}

type orderServiceClient struct {
	c           client.Client
	serviceName string
}

func NewOrderServiceClient(serviceName string, c client.Client) OrderServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "model.order"
	}
	return &orderServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...client.CallOption) (*CreateOrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.CreateOrder", in)
	out := new(CreateOrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrders(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetOrdersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetOrders", in)
	out := new(GetOrdersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	CreateOrder(context.Context, *Order, *CreateOrderResponse) error
	GetOrders(context.Context, *GetRequest, *GetOrdersResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&OrderService{hdlr}, opts...))
}

type OrderService struct {
	OrderServiceHandler
}

func (h *OrderService) CreateOrder(ctx context.Context, in *Order, out *CreateOrderResponse) error {
	return h.OrderServiceHandler.CreateOrder(ctx, in, out)
}

func (h *OrderService) GetOrders(ctx context.Context, in *GetRequest, out *GetOrdersResponse) error {
	return h.OrderServiceHandler.GetOrders(ctx, in, out)
}
